name: Build and Deploy Website

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Verify resources directory
    - name: Verify Resources Directory
      run: |
        echo "Listing repository root:"
        ls -R .
        echo "Listing resources directory:"
        ls -R ./resources

    # Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16

    # Install dependencies
    - name: Install Dependencies
      working-directory: ./website
      run: npm install

    # Clear Cache
    - name: Clear Cache
      working-directory: .
      run: npm rebuild node-sass

    # Sync resources
    - name: Sync Resources
      working-directory: .
      run: node sync-resources.js

    # Build the website
    - name: Build Website
      working-directory: ./website
      run: npm run build

    # Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./website/build
