name: Sync Resources

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync-resources:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Debug: List repository structure
    - name: List Repository Structure
      run: |
        echo "Listing repository root:"
        ls -R .
        echo "Listing resources directory:"
        ls -R ./resources

    # Set up Node.js (use Node.js >=18.0)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # Install dependencies
    - name: Install Dependencies
      working-directory: ./website
      run: npm install

    # Sync resources
    - name: Sync Resources
      working-directory: .
      run: node sync-resources.js
